### PR TITLE
phytec-test-image: Add chrony package for NTP usage

### PR DESCRIPTION
**Pull request by ctenruh-phytec**
Add chrony package to sync time using NTP. Delete ntp package to avoid
conflict.

Signed-off-by: Cem Tenruh <c.tenruh@phytec.de>

### CODE REVIEW

**Comment by mschwan-phytec** [comment]
I guess that this just configures the usual NTP servers and not SNTP. Did you find anything related to using SNTP? If so please include this configuration in this PR.

**Comment by mschwan-phytec** [comment]
~Please also check systemd-timesyncd. It should support SNTP since version 213: https://lists.freedesktop.org/archives/systemd-devel/2014-May/019537.html Reading the notes there this may have the advantage of a smaller client without any server, which we do not need at the moment. Personally, I would prefer using the systemd's own services because we are already using others from systemd.~

I think we are confusing SNTP with NTS here. :see_no_evil: For systemd see https://github.com/systemd/systemd/issues/9481 and https://github.com/systemd/systemd/pull/17778. So NTS support is not yet merged in systemd, as of this time.

**Comment by mschwan-phytec** [comment]
We decided to postpone NTS support for a later stage, as there are other issues that arise with using NTS.

@ctenruh-phytec Please rebase your branch onto the current zeus branch, so I can merge this.

**Review by mschwan-phytec — APPROVED** [review]
LGTM

**Comment by ctenruh-phytec** [comment]
> We decided to postpone NTS support for a later stage, as there are other issues that arise with using NTS.
> 
> @ctenruh-phytec Please rebase your branch onto the current zeus branch, so I can merge this.

done

**Pull request merged**
